language: python

notifications:
  email: false

env:
  global:
    - TWINE_USERNAME=dwtools
    - secure: fCR2dl2rOpQskPO+6Y77LdAYqx9suMmqp0b47ONxDh1PzucNpL1H5e8jI2CZ1tKh61rT6dP7KGJUR22znpkEDzIcZwQ6yOShHzmFFdU0XVvK+HYFpgCCKAMQ+QYHR9jS37CBrT3Mw7PKgJu6Qt/GenI/yIk/2iBYhw+L72SwokYxWi5EJ7e854TD6ivHu8teSp7KV41xhWf+hWrF8KIBNz48YQu1U4mJ0pkwmJLvfsg/IAJrrGt1EVzGQk3K3+FkFdhbYDTl5Py8fLs76LQvF4+z8JWX/xWDs5AbiwIaIdezY1jnuCGQN0Dn/O4QVEm5aCR6zSqabSbZZtMIhzdB9BN4GlxNAKQfoLmiA7JWlHz2ZAhk4Ic8CJJAzU5ynoq49IDisE1bFVH1LbPOUcoRwhJbdmJRcvU8n1nl7QsfWZo0xglwsnvmtbIqdhIU8nyL+X2CR5o7HXYi7B4/g+5ZEJ7k53MKYSPo211QO7MK25Cp/vwkPe3NQ8xpI/8AO8+lQP0IfExj1s0XPwviUaQqBpPUDgs/I0NaJDp9jWgN0M1fE+NFMdl9fADYpwpP4gDAcY5Pu6m7C6oKx3BHVJp9ZDI8qvN3bB6BMTx18do5DUiIXXNFIEpiwt5o1MiBzpWnjAilzYa1WDpCh9Eqo7ar3tI32J0amEtdOSMhNPNO5KU=

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32

install:
  - docker pull $DOCKER_IMAGE
  - pip install coveralls

script:
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
  - ls wheelhouse/

after_success:
  - pip install -r requirements.txt dwave_sage --no-index -f wheelhouse/
  - coverage run --source=dwave_sage -m unittest discover
  - coveralls

deploy:
  provider: script
  script: travis/upload-wheels.sh
  skip_cleanup: true
  on:
    tags: true
    branch: master
