language: python

notifications:
  email: false

env:
  global:
    - TWINE_USERNAME=dwtools
    - secure: "Dv/S55P1YBWhu2rl7BRzMbvhMWEkSdTGEUiAcP1UAEosR2GbQo8Rh3TkYaksLm4KV+9kLew0/aibg7bZYxzQr6WjNtTwf+JIb7XZi+/dtlp+WmoMZQLaNev0kjekTsOIrqAOBCIX6P6FcYGAWy5YvIHXqLp9ejCKk3wOOEGItfur4noTS+8XmA4NPVaOezVi51ehHHQPls9n8YZPYlkYrxkbGQvx038aGdbmDNbKwaP/FTywuwarsq8Ye/RCAjxRdKJuRlHsLQA8WSMFa2Yg7SA4+G6dsf92AcIKPZYZeZLmkypYU0z/3V6//7o18ukm1EEsuhgLoIvt5DqlhNC32gqCEPoI/E+hphWRsbAoej54XVYFSM115XV5OtOVIGYoABppIuZqtXIiyZvuNf6wjM//Cs6LefdVFwkYTcp899zHDkHyX2sTU6eZI30yw0dPNe5EdAnin6ulnuwfKUAMvloMuClQaRx+wySNZ/bZN5hxefJfPbobHnhgWq1IEHSYE7m12ZQqBFuMonqgrdd5ZiAhbubYsWaxI3Ee5hKuXlJXpyT9lZohzqhIsA4SLbGlF9NWagrQpb4zGlwxtoGbGBL2knQw4nA4XhPnEncYuLt/xVQs3u01BnEl+Gmo2rUfMdq+aJgARxihZgXYFFzJfUxrcdD2Vm17wdphgHgc9iA="

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
  - ls wheelhouse/

deploy:
  provider: script
  script: travis/upload-wheels.sh
  skip_cleanup: true
# on:
#   tags: true
#   branch: master
