language: python

notifications:
  email: false

env:
  global:
    - TWINE_USERNAME=dwtools
    - secure: LkzSCk2wgL4psvc2r3UjI1ikthVip0H25sH585P49dwGR0ZRtvczQEcmSOTnUtTwVUFGKuNe6mXiCpDNI/LUvDNtg28iYm6XptGQHlohPNiysPAxMGjYtJ7iq+ONA5i5YyqeKfSg4jZcCzzwMxyEK7oN/4jvwhez96qwe9amYOVhqsa2kqUcNLobwbAtuGrdFmb9A0RfulD1d59UgOHrBIWP/x36pmQKPP2SPzHCyfpn9PY3zjVd237+G6MSlZGZV6qa+0BVIbK+2swislL1ETxkhE3tuSUkw+kz5UmmMt+ph2DoA0q4w8TkzzoJrBC3nSJyRkaNIefxudFhmyD0136UDqJVMoNJB4xNM5SHpjLtDOPD4CQ/FwClFy0UIPRbT9SAl1pqG2ORE/28FgXil96TJy8R8YWQHGTeYfWZjhWWiLF/LW953Zyy6GgtGf04csiySxUthyA2ZibJxT5699RP765HZKgNxx2XBZ8h3qikccg5i9BRK5WXbukHNVuwyNjnTP5zngUuNzQNmqtpOFA7h5C1fy0nD4oG4JWS6TJGXgs144F+uj/omXjd+crVLml2sejJpK3iSrBkDhDZrcdy0GR15hG241tEkgfa6yLTLsTkYkAyqGuQ/w4r7XSujiN/pO0xfrZVkI2zWBBSkXxzAI0OcdQJzLtrSXp5vlA=

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
  - ls wheelhouse/

deploy:
  provider: script
  script: travis/upload-wheels.sh
  skip_cleanup: true
# on:
#   tags: true
#   branch: master
